server:
  port: 8999

spring:
  application:
   name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**

        - id: AccountService
          uri: lb://AccountService
          predicates:
            - Path=/account/**

        - id: TransactionService
          uri: lb://TransactionService
          predicates:
            - Path=/transaction/**

        - id: LoanService
          uri: lb://loanService
          predicates:
            - Path=/loan/**