server:
  port: 8999

spring:
  application:
   name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**

        - id: AccountService
          uri: lb://AccountService
          predicates:
            - Path=/Account/**

        - id: TransactionService
          uri: lb://TransactionService
          predicates:
            - Path=/Transaction/**

        - id: LoanService
          uri: lb://LoanService
          predicates:
            - Path=/Loan/**